In [3]:
import pandas

In [4]:
dataset = pandas.read_csv('marks.csv')

In [6]:
dataset

hrs  marks
0    2     20
1    7     70
2    3     30
3    6     60

In [7]:
# y : outcome: target : DV
y = dataset['marks']

In [8]:
# x : IV :  predictor
x = dataset['hrs']

In [10]:
type(x)

pandas.core.series.Series

In [11]:
x1 = x.values

In [12]:
x1

array([2, 7, 3, 6], dtype=int64)

In [14]:
x = x.values.reshape(-1, 1)

In [15]:
x

array([[2],
       [7],
       [3],
       [6]], dtype=int64)

In [16]:
from sklearn.linear_model  import LinearRegression

In [17]:
model = LinearRegression()

In [18]:
model.fit(x , y)

LinearRegression()

In [19]:
model

LinearRegression()

In [20]:
model.coef_

array([10.])

In [21]:
model.predict([[ 9 ]])

array([90.])

In [22]:
db = [ [1, "arnav", "ok"] , [2, "pop", "good"] , [3 , "tom", "good"]  ]

In [23]:
db[0]

[1, 'arnav', 'ok']

In [24]:
db[0][1]

'arnav'

In [25]:
type(db)

list

In [26]:
import numpy

In [27]:
# 2D : matrix
a = numpy.array([ [1, "arnav", "ok"] , [2, "pop", "good"] , [3 , "tom", "good"]  ])

In [28]:
a

array([['1', 'arnav', 'ok'],
       ['2', 'pop', 'good'],
       ['3', 'tom', 'good']], dtype='<U11')

In [29]:
a[2][1]

'tom'

In [30]:
# 1D : vector
b = numpy.array(["a", "b", "c", "d"])

In [31]:
b


array(['a', 'b', 'c', 'd'], dtype='<U1')

In [32]:
d = b.reshape(-1, 1)

In [33]:
d.shape

(4, 1)

In [34]:
d

array([['a'],
       ['b'],
       ['c'],
       ['d']], dtype='<U1')